config/routes.rb
BillClinton::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :activities
  
  root 'static_pages#home'
  match '/activities', to: 'activities#home', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, length: {maximum: 50}

  validates :password, length: { minimum: 6 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  
  before_save { self.email = email.downcase }

  has_secure_password

  before_create :create_remember_token

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.hash(User.new_remember_token)
    end


end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
  end

  def create 
    @activity = Activity.new(activity_params)
    if @activity.save
      flash[:success] = "Check this out!"
      redirect_to @activity
    else 
      render 'new'
    end
  end 

  def new
    @activity = Activity.new
  end

  def show
    @activity = Activity.find(params[:id])
  end

  private
  
  def activity_params
    params.fetch(:activity, {}).permit(:name, :yob)
  end
end
 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to Gages Site yo!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper

  def years_lived
    yob = @activity.yob
    if yob == 1994
       "we were born the same year!"
    elsif yob >1994
      "you are younger than me"
    else 
      "you are older than me!"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title)
    base_title = "Bill Clinton"

    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.hash(remember_token))
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.hash(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.hash(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/activities/index.html.erb
<% provide(:title, "Activities") %>
<h1>Fun Activities</h1>

app/views/activities/new.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@activity) do |f| %>

      <%= f.label :yob , 'Year of Birth'%>
      <%= f.text_field :yob %>

      <%= f.label :name, 'Full Name' %>
      <%= f.text_field :name %>

      <%= f.submit "See the magic", class: "btn btn-small btn-primary" %>
    <% end %>
  </div>
</div>

app/views/activities/show.html.erb
<h2> What I can do just from those 2 inputs! <b>Be amazed</b></h2>



<ul>
  <li>Your name is: <b><%=@activity.name.reverse.upcase%></b> spelled backwards.</li>
  <li>Your name is <b><%=@activity.name.length-1%></b> characters long.</li>
  <li>Print your name multiple times.... <%=(@activity.name+ " ") * 6%></li>
  <li>My birthday is in 1994 meaning <%=years_lived%></li>
  <li>You are roughly <%=Time.now.year - @activity.yob%> years old!</li>
</ul>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Personal Site
    by Gage Shaeffer
  </small>
  <nav>
    <ul>
      <li><%= link_to "Twitter",   href="https://twitter.com/gageywagey" %></li>
      <li><%= link_to "Facebook", href="https://www.facebook.com/gage.shaeffer.7" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "<!Gage>", '#', id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", about_path%></li>
          <li><%= link_to "Fun", new_activity_path%></li>
          <li><%= link_to "Contact", contact_path%></li>
          <% if signed_in? %>
            <li><%= link_to "Users", '#' %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= @current_user.name %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
  </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>Scholar. Juggling-Pro. Coding Connoiseur.</h1>

<p>
  At 16, I was introduced to html by having text appear on a computer screen. The days following included being in front of a computer, coding anything and everything that I could in hopes of learning this amazing new concept. The love for computers grew from that point on drastically.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact Us</h1>

app/views/static_pages/help.html.erb
<% provide(:title, 'Fun') %>
<h1>Fun Programs</h1>
<div class="row">
  <div class="span6 offset3">
<form id="birth_year">
  <input type="text">
  <button type="button" onclick="life_time()">Calculate</button>
</form>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
<!--  Carousel - consult the Twitter Bootstrap docs at 
      http://twitter.github.com/bootstrap/javascript.html#carousel -->
      <h2>My Life.</h2>
<div id="this-carousel-id" class="carousel slide"><!-- class of slide for animation -->
  <div class="carousel-inner">
    <div class="item active"><!-- class of active since it's the first item -->
      <%= image_tag("cincy.jpg", alt: "Cincinnati 513") %>
      <div class="carousel-caption">
        <p>Hello World</p>
      </div>
    </div>
    <div class="item">
      <%= image_tag("uc.png", alt: "University of Cincinnati") %>
      <div class="carousel-caption">
        <p>Caption text here</p>
      </div>
    </div>
    <div class="item">
      <%= image_tag("uc.png", alt: "University of Cincinnati") %>
      <div class="carousel-caption">
        <p>Caption text here</p>
      </div>
    </div>
    <div class="item">
      <%= image_tag("uc.png", alt: "University of Cincinnati") %>
      <div class="carousel-caption">
        <p>Caption text here</p>
      </div>
    </div>
  </div><!-- /.carousel-inner -->
  <!--  Next and Previous controls below
        href values must reference the id for this carousel -->
    <a class="carousel-control left" href="#this-carousel-id" data-slide="prev">&lsaquo;</a>
    <a class="carousel-control right" href="#this-carousel-id" data-slide="next">&rsaquo;</a>
</div><!-- /.carousel -->

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password, "Password (Must be 6 characters)" %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>